"""
app/whatsapp_sender.py
----------------------
Send a report PDF via the Twilio WhatsApp API.

The PDF is first uploaded as a publicly accessible URL — however, Twilio's
WhatsApp sandbox and approved templates allow sending MMS attachments via
``media_url``.  Because this application serves the PDF itself, the function
builds a fully-qualified URL from the Flask request context and passes it to
Twilio, which fetches and forwards it to WhatsApp.

Required environment variables
-------------------------------
TWILIO_ACCOUNT_SID     Twilio Account SID
TWILIO_AUTH_TOKEN      Twilio Auth Token
TWILIO_WHATSAPP_FROM   Twilio sandbox / approved sender number in E.164 format,
                       prefixed with ``whatsapp:``
                       Example: whatsapp:+14155238886
LOGGUARD_PUBLIC_URL    Base URL of this application reachable by Twilio
                       (e.g. https://yourapp.example.com).  Required so Twilio
                       can fetch the PDF attachment.
"""

from __future__ import annotations

import os


class WhatsAppSenderError(Exception):
    """Raised when WhatsApp sending fails due to configuration or API errors."""


def send_report_whatsapp(
    to_number: str,
    run_id: int,
    pdf_url: str,
    *,
    body: str | None = None,
) -> None:
    """Send a WhatsApp message with a link to the PDF report.

    Parameters
    ----------
    to_number:
        Recipient phone number in E.164 format, e.g. ``+447911123456``.
        The ``whatsapp:`` prefix is added automatically if absent.
    run_id:
        Numeric run identifier (used in the default message body).
    pdf_url:
        Publicly accessible URL of the PDF file; passed to Twilio as
        ``media_url`` so it is forwarded as a media attachment.
    body:
        Optional override for the WhatsApp message text.

    Raises
    ------
    WhatsAppSenderError
        When Twilio credentials are missing, the number is invalid, or the
        API call fails.
    """
    account_sid = os.environ.get("TWILIO_ACCOUNT_SID", "").strip()
    auth_token = os.environ.get("TWILIO_AUTH_TOKEN", "").strip()
    from_number = os.environ.get("TWILIO_WHATSAPP_FROM", "").strip()

    if not account_sid or not auth_token or not from_number:
        raise WhatsAppSenderError(
            "WhatsApp is not configured. Set TWILIO_ACCOUNT_SID, "
            "TWILIO_AUTH_TOKEN, and TWILIO_WHATSAPP_FROM environment variables."
        )

    # Normalise numbers to whatsapp: prefix
    if not to_number.startswith("whatsapp:"):
        to_number = f"whatsapp:{to_number}"
    if not from_number.startswith("whatsapp:"):
        from_number = f"whatsapp:{from_number}"

    body = body or (
        f"LogGuard Anomaly Detection Report — Run #{run_id}\n"
        "Please find the attached PDF report generated by LogGuard."
    )

    try:
        from twilio.rest import Client  # imported lazily so the app starts without twilio
        from twilio.base.exceptions import TwilioRestException
    except ImportError as exc:
        raise WhatsAppSenderError(
            "The 'twilio' package is required to send WhatsApp messages. "
            "Install it with: pip install twilio"
        ) from exc

    try:
        client = Client(account_sid, auth_token)
        client.messages.create(
            body=body,
            from_=from_number,
            to=to_number,
            media_url=[pdf_url],
        )
    except TwilioRestException:  # type: ignore[possibly-undefined]
        raise WhatsAppSenderError(
            "Failed to send WhatsApp message via Twilio. "
            "Check your Twilio credentials and that the recipient number is valid."
        ) from None
