"""
app/whatsapp_sender.py
----------------------
Send a report PDF via the 360dialog WhatsApp Business API.

The PDF is shared as a publicly accessible URL which is passed to the
360dialog API as a document link attachment.  Because this application
serves the PDF itself, the function builds a fully-qualified URL from the
Flask request context and passes it to the API.

Required environment variables
-------------------------------
WHATSAPP_API_KEY           API key obtained from the 360dialog Hub
                           (https://hub.360dialog.com/).
LOGGUARD_PUBLIC_URL        Base URL of this application reachable by 360dialog
                           (e.g. https://yourapp.example.com).  Required so
                           the API can fetch the PDF attachment.

Optional environment variables
-------------------------------
WHATSAPP_API_URL           Base URL for the 360dialog API
                           (default: https://waba.360dialog.io/v1/messages).
"""

from __future__ import annotations

import os

import requests

_DEFAULT_API_URL = "https://waba.360dialog.io/v1/messages"


class WhatsAppSenderError(Exception):
    """Raised when WhatsApp sending fails due to configuration or API errors."""


def send_report_whatsapp(
    to_number: str,
    run_id: int,
    pdf_url: str,
    *,
    body: str | None = None,
) -> None:
    """Send a WhatsApp message with a PDF report link via 360dialog.

    Parameters
    ----------
    to_number:
        Recipient phone number in E.164 format, e.g. ``+447911123456``.
        The leading ``+`` is stripped automatically as the API expects
        digits only (e.g. ``447911123456``).
    run_id:
        Numeric run identifier (used in the document caption).
    pdf_url:
        Publicly accessible URL of the PDF file; sent as a document link
        attachment via the 360dialog WhatsApp API.
    body:
        Optional override for the document caption text.

    Raises
    ------
    WhatsAppSenderError
        When credentials are missing, the number is invalid, or the API
        call fails.
    """
    api_key = os.environ.get("WHATSAPP_API_KEY", "").strip()

    if not api_key:
        raise WhatsAppSenderError(
            "WhatsApp is not configured. Set the WHATSAPP_API_KEY environment variable "
            "with your 360dialog API key."
        )

    # The API requires the recipient number in E.164 digits-only form
    # (no leading + sign, no spaces or dashes).
    recipient = to_number.lstrip("+").replace(" ", "").replace("-", "")
    if not recipient.isdigit():
        raise WhatsAppSenderError(
            f"Invalid recipient phone number: '{to_number}'. "
            "Provide the number in E.164 format, e.g. +447911123456."
        )

    caption = body or (
        f"LogGuard Anomaly Detection Report — Run #{run_id}\n"
        "Please find the attached PDF report generated by LogGuard."
    )

    api_url = os.environ.get("WHATSAPP_API_URL", _DEFAULT_API_URL).strip()

    payload = {
        "to": recipient,
        "type": "document",
        "document": {
            "link": pdf_url,
            "caption": caption,
            "filename": f"logguard_report_run_{run_id}.pdf",
        },
    }

    headers = {
        "D360-API-KEY": api_key,
        "Content-Type": "application/json",
    }

    try:
        response = requests.post(api_url, json=payload, headers=headers, timeout=30)
    except requests.RequestException as exc:
        raise WhatsAppSenderError(
            "Network error while contacting the 360dialog WhatsApp API. "
            f"Details: {exc}"
        ) from exc

    if not response.ok:
        try:
            detail = response.json().get("error", {}).get("message", response.text)
        except ValueError:
            detail = response.text
        raise WhatsAppSenderError(
            f"360dialog WhatsApp API returned HTTP {response.status_code}: {detail}"
        )
